# config/_default/menus.toml


[[main]]
  name = "Jobs"
  parent = "Join Us"
  pageRef = "jobs"
  weight = 20

[[main]]
  name = "MSc / BSc Thesis"
  parent = "Join Us"
  pageRef = "theses"
  weight = 20

[[main]]
  name = "Project Students"
  parent = "Join Us"
  pageRef = "projectstudents"
  weight = 20

[[main]]
  name = "News"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Group"
  weight = 20
  pageRef = "group"

[[main]]
  name = "Research"
  weight = 20

[[main]]
  name = "Publications"
  parent = "Research"
  pageRef = "publications"
  weight = 20

[[main]]
  name = "Software"
  parent = "Research"
  pageRef = "Software"
  weight = 20

[[main]]
  name = "ATLAS"
  parent = "Research"
  pageRef = "ATLAS"
  weight = 20

[[main]]
  name = "Funding"
  parent = "Research"
  pageRef = "Funding"
  weight = 999


[[main]]
  name = "Teaching"
  weight = 20
  pageRef = "teaching"


[[main]]
  name = "Join Us"
  weight = 35

[[main]]
  name = "Contact"
  weight = 40
  pageRef = "contact"


[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/tupheds/tupheds_website"
  weight = 99


