baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Data Science in Physics Lab'
theme = 'blowfish'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"